### PR TITLE
Add /api/** to SecurityFilterChain requestmatcher for PermitAll

### LINKED ISSUE #71: Cannot access our rest-apis after implementation of security.
**Describe the bug**
Cannot access our rest-apis after implementation of security.

**To Reproduce**
1. User Insomnia/Postman
2. Go to http://localhost:8080/api/messages
3. See that you have to log in through GitHub.

**Expected behavior**
We should be able reach the /api/ endpoints without logging in with github.

### PR DESCRIPTION
**Pull request by Win-ther**
### Related Issue(s)
Closes #71 

### Proposed Changes
- Added /api/** to SecurityFilterChains permitAll RequestMatcher.

### Description
With this fix we can now access all our RESTapi endpoints.

### CODE REVIEW

**Review by altmannk — APPROVED** [review]
👌🏼 noice

**Review by marcusju23 — APPROVED** [review]
Good job! 👍

**Review by altmannk — COMMENTED** [review]
Hmm should we have multiple SecurityFilters?

image

**Comment by Win-ther** [comment]
> Hmm should we have multiple SecurityFilters?
> 


I was trying it out at first because I thought it was necessary, but I could not get it to work. But I realized that it isn't really necessary since we only have GET-endpoints in /api/** and adding it to the permitAll requestMatchers would be simpler to fix the bug. 

We can absolutely implement it if we want to change the session management to stateless and if we want to disable CSRF, or even if we want to use JWTs as Martin showed. But that should be in its own Issue since this is a PR for the bug that happened when we implemented Oauth2.

**Review by Frlundsten — APPROVED** [review]
Great 👍

**Pull request merged**
