### PR TITLE
Create README.md

### LINKED ISSUE #50: Add README.md

### PR DESCRIPTION
**Pull request by Win-ther**
### Related Issue(s)
Closes #50 

### Proposed Changes
- Add a simple Readme with instructions and webpages

### CODE REVIEW

**Review by altmannk — APPROVED** [review]
Concise and simple 💯

**Comment by Frlundsten** [comment]
We gilgang now?

**Comment by Win-ther** [comment]
> We gilgang now?

Yes? No? Do you want it to say Gilfgang? To be fair we have used Gilgang, Gilfgang and Ggang pretty loosely in the project :P

**Comment by Frlundsten** [comment]
> > We gilgang now?
> 
> Yes? No? Do you want it to say Gilfgang? To be fair we have used Gilgang, Gilfgang and Ggang pretty loosely in the project :P

What a mess! ok we gilgang.

**Review by Frlundsten — APPROVED** [review]
10/10 signed the masterpiece.

**Review by marcusju23 — APPROVED** [review]
Solid! 👍

**Pull request merged**
