### PR TITLE
Refactor se.iths.SpringbootGroupProject to lowercase

### LINKED ISSUE #37: Package names should comply with a naming convention
**Describe the bug**

> Shared naming conventions improve readability and allow teams to collaborate efficiently. This rule checks that all package names match a provided regular expression.

**How to fix**

> Rename packages with the expected naming convention
> Noncompliant code example
> With the default regular expression ^[a-z_]+(\.[a-z_][a-z0-9_]*)*$:

In short just refactor `se.iths.SpringbootGroupProject` to lowercase, so `se.iths.springbootgroupproject` instead. 

**To Reproduce**
1. Commit anything with **SonarLint**
2. See error

**Desktop**
 - OS: [W11]
 - IDE: IntelliJ IDEA 2023.3.5

**Additional context**
Just a minor inconvenience.

### PR DESCRIPTION
**Pull request by marcusju23**
### Related Issue(s)
Closes #37 

### Proposed Changes
- Refactor se.iths.SpringbootGroupProject to lowercase

### Description
Check #37 for further information.

### CODE REVIEW

**Review by Win-ther — DISMISSED** [review]
Good fix! 
ed1nyii7y8h41

**Comment by marcusju23** [comment]
I'm temporarily drafting this until we successfully merge PR #36 to preemptively resolve any future conflicts.

**Review by altmannk — APPROVED** [review]
very satisfying change ^_^

**Review by Win-ther — APPROVED** [review]
👍

**Review by Frlundsten — APPROVED** [review]
Nice

**Pull request merged**
