### PR TITLE
Refactor with LOMBOK

### LINKED ISSUE #78: Standard for Entities and DTOs with Lombok.
As it is right now we have mixed using Lombok and not using Lombok in Entities/DTOs. We should refactor our code to either actually use Lombok annotations, or remove it from our project and just use normal Getter/Setter/Constructor methods.
What do you think?

### PR DESCRIPTION
**Pull request by Win-ther**
### Related Issue(s)
Closes #78 

### Proposed Changes
- Refactor entities and dtos with Lombok.
- Add JPA-utilities generated Equals/Hashcode to Message to follow same standard as User.

### Description
image

### CODE REVIEW

**Comment by Win-ther** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84) **Quality Gate failed**
> Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_coverage&view=list) (required ≥ 80%)  [14.6% Duplication on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84)

Why no coverage on equals and hashcode? :C I will try implementing EqualsVerifier to see if it gets coverage then (https://jqno.nl/equalsverifier/)

**Comment by Frlundsten** [comment]
> > ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84) **Quality Gate failed**
> > Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_coverage&view=list) (required ≥ 80%)  [14.6% Duplication on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> > [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84)
> 
> Why no coverage on equals and hashcode? :C I will try implementing EqualsVerifier to see if it gets coverage then (https://jqno.nl/equalsverifier/)

Really nice refactoring, so clean 🤤 
It might be hard to get full coverage since it seem that you would have to mock hibernate somehow to load the entities as hibernate proxies.  Maby the link you provided will be able to solve it. Worth a try 👍 Otherwise maby an end to end test would work since it would not ommit any functionality of the application, but it would need some work to implement I think..

Another thing I think about now that we have Lombok annotations is that the entities getter and setters tests feel redundant. Since they are generated through a dependency there is no way for us to implement bugs into them. What do you think about it?

These are just thoughts. I think this looks great as it is, good job😄

**Review by Frlundsten — DISMISSED** [review]

**Comment by Frlundsten** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84) **Quality Gate failed**
> Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_coverage&view=list) (required ≥ 80%)  [12.5% Duplication on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84)
> 
> OKAY SonarCloud does not like testing Equals and HashCode. I think it is good to override the Equals And Hashcode methods, since Equals should rely on the PrimaryKey (ID) and nothing else, but maybe the equals-verifier testing is unnecessary? Should I revert the commit so that we just use normal testing for the methods?

Since it didnt do any difference we should probably go back.

**Comment by altmannk** [comment]
> Another thing I think about now that we have Lombok annotations is that the entities getter and setters tests feel redundant. Since they are generated through a dependency there is no way for us to implement bugs into them. What do you think about it?

I agree!

**Comment by Win-ther** [comment]
> > Another thing I think about now that we have Lombok annotations is that the entities getter and setters tests feel redundant. Since they are generated through a dependency there is no way for us to implement bugs into them. What do you think about it?
> 
> I agree!

Okay, I will remove equals-verifier and remove Getter and Setter tests.

**Comment by Win-ther** [comment]
> > > ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84) **Quality Gate failed**
> > > Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_coverage&view=list) (required ≥ 80%)  [14.6% Duplication on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> > > [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84)
> > 
> > 
> > Why no coverage on equals and hashcode? :C I will try implementing EqualsVerifier to see if it gets coverage then (https://jqno.nl/equalsverifier/)
> 
> Really nice refactoring, so clean 🤤 It might be hard to get full coverage since it seem that you would have to mock hibernate somehow to load the entities as hibernate proxies. Maby the link you provided will be able to solve it. Worth a try 👍 Otherwise maby an end to end test would work since it would not ommit any functionality of the application, but it would need some work to implement I think..
> 
> Another thing I think about now that we have Lombok annotations is that the entities getter and setters tests feel redundant. Since they are generated through a dependency there is no way for us to implement bugs into them. What do you think about it?
> 
> These are just thoughts. I think this looks great as it is, good job😄

One problem is, we are not getting coverage for the fields in IntelliJ. Do we care about this? Should we still remove the getter and setter tests?
image

**Comment by Frlundsten** [comment]
> > > > ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84) **Quality Gate failed**
> > > > Failed conditions  [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_coverage&view=list) (required ≥ 80%)  [14.6% Duplication on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=84&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> > > > [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=84)
> > > 
> > > 
> > > Why no coverage on equals and hashcode? :C I will try implementing EqualsVerifier to see if it gets coverage then (https://jqno.nl/equalsverifier/)
> > 
> > 
> > Really nice refactoring, so clean 🤤 It might be hard to get full coverage since it seem that you would have to mock hibernate somehow to load the entities as hibernate proxies. Maby the link you provided will be able to solve it. Worth a try 👍 Otherwise maby an end to end test would work since it would not ommit any functionality of the application, but it would need some work to implement I think..
> > Another thing I think about now that we have Lombok annotations is that the entities getter and setters tests feel redundant. Since they are generated through a dependency there is no way for us to implement bugs into them. What do you think about it?
> > These are just thoughts. I think this looks great as it is, good job😄
> 
> One problem is, we are not getting coverage for the fields in IntelliJ. Do we care about this? Should we still remove the getter and setter tests? image

I don't think its correct to get coverage of something just to get coverage. If you feel the need of testing the getters and setters  and test their functionality you should probably do that.

**Comment by Win-ther** [comment]
> 
> I don't think its correct to get coverage of something just to get coverage. If you feel the need of testing the getters and setters and test their functionality you should probably do that.

Okay, I removed all Getter/Setter/NoArgsConstructor/AllArgsConstructor tests, since these are all implemented with Lombok-annotations. Do not think it's a big deal anyway and we can always revert the commit later if we changed our mind :)

**Review by altmannk — APPROVED** [review]
Looks good! 🦖  Think this was the right choice too.

**Review by Frlundsten — APPROVED** [review]
10/10 would review again.

**Review by marcusju23 — APPROVED** [review]
Very nice refactor! 🌟

**Pull request merged**
