### PR TITLE
22 add sonarcloud to pipeline

### LINKED ISSUE #22: Add SonarCloud to pipeline

### PR DESCRIPTION
**Pull request by marcusju23**
### Related Issue(s)
Closes #22 

### Proposed Changes
- Add SonarCloud build to `pipeline.yml`
- Add Coverage profile in `pom.xml` for jacoco plugin
### Additional Changes
- Set source file encoding to UTF-8
- Update Java compiler release version to 21

### Description
These changes enable SonarCloud's Coverage feature in our project. By adding SonarCloud to the pipeline and configuring Jacoco to generate coverage reports, we enhance code analysis and ensure better quality and maintainability.

### CODE REVIEW

**Comment by marcusju23** [comment]
First try btw

**Review by Frlundsten — APPROVED** [review]
Flawless

**Review by Win-ther — APPROVED** [review]
Good job, and on the first try aswell. I can't believe this was implemented successfully without any pain and suffering at all.

**Review by altmannk — APPROVED** [review]
let her sail 🫡

**Pull request merged**
