### PR TITLE
70 add services tests

### LINKED ISSUE #70: Add services tests

### PR DESCRIPTION
**Pull request by marcusju23**
### Related Issue(s)
Closes #70

### Proposed Changes
- Add tests for `LibreTranslateService`
- Add tests for `MessageService`
- Add tests for `UserService`

### Description
I attempted to create tests for `GithubOAuth2UserService`, but my efforts were unsuccessful. @vonfredd and I have done manual testing. If anyone wishes to attempt writing tests for it, please feel free to do so.

### CODE REVIEW

**Review by Win-ther — DISMISSED** [review]
This is a massive amount of tests, great job! They look good and well structured, some of  them are quite big but I see the reason behind it. Approving, good job! 😁

**Review by altmannk — CHANGES_REQUESTED** [review]
I suggest that we remove the LibreTranslate test because it does not test the right things and it's deadline tomorrow. The other tests looks really good, great job! ⭐

**Review by altmannk — APPROVED** [review]
Awesome! ⭐

**Review by Win-ther — APPROVED** [review]
Good job!

d_y8Kl

**Review by Frlundsten — APPROVED** [review]
Noice 👍

**Pull request merged**
