### PR TITLE
40 modifying annotation in repository should only return void or int / small refactor and update

### LINKED ISSUE #40: Modifying annotation in repository should only return void or int
**Describe the bug**
Apparently the return type for Modifying annotation is void or int.
Meaning if it's an int, the return value will be the number of rows that where updated in the database.
Currently we have String as return type.

**Where**
to find it:
- 'src/main/java/repositories/MessageRepository'
- 'src/main/java/repositories/UserRepository'

**Screenshots**
image

image

### LINKED ISSUE #42: Small refactor and update
**General refactoring**
- Remove unused import in GuestController class. 
- Add debug command to application.properties to be able to check database communication.
- Proper projection through DTO, removing N+1 problem while loading data.

### PR DESCRIPTION
**Pull request by Frlundsten**
### Related Issue
Closes #42
Closes #40

## Update returnvalues
- Modifying methods now returns void.

## General refactoring
- Remove unused import in GuestController class.
- Add debug command to application.properties to be able to check database communication.
- Proper projection through DTO, removing N+1 problem while loading data. Change parameter names to prevent **PropertyReferenceException**.
- Refactor messageService.findAllByPrivateMessageIsFalse() because of DTO projection in repository.

### CODE REVIEW

**Review by marcusju23 — DISMISSED** [review]
noice 👍

**Review by Win-ther — DISMISSED** [review]
Looks good :)

**Review by marcusju23 — APPROVED** [review]
👏

**Review by Win-ther — APPROVED** [review]
image

**Review by altmannk — APPROVED** [review]
image

**Pull request merged**
