### PR TITLE
Add a way to delete messages from the edit-form.

### LINKED ISSUE #87: Delete message
Add a way to delete messages.

### PR DESCRIPTION
**Pull request by Win-ther**
### Related Issue(s)
Closes #87 

### Proposed Changes
- Add a button to the edit form, where if you click it the message is now deleted and you are redirected to /myprofile.

### Description
Add a button to /editmessage to delete the message.

### CODE REVIEW

**Review by altmannk — DISMISSED** [review]
I like it! Nice 😃

**Review by altmannk — APPROVED** [review]
👍🏽 gütt!

**Review by marcusju23 — APPROVED** [review]
7A1x 👍

**Review by Frlundsten — APPROVED** [review]
GJ

**Pull request merged**
